### ISSUE TITLE
Ready to test?

### ISSUE THREAD

**Issue by SpaceK33z** [fcsonline/react-transmission#23]
Hey,
sorry for breaking in like this. I just saw this project after some searching ([via here](https://twitter.com/BcnJS/status/823958627929227264)), and I'm in desperate need of a better Transmission Web UI. Would you think this is ready to use, or is it missing huge features? I can help test a bit if you'd like.

Btw, I'm a core team member of webpack, so if you need any help with webpack-related stuff, let me know!

**Comment by fcsonline** [comment]
It's ready to test. Around a 98% of features from the original UI are implemented. To test it just start your Transmission and go through the steps described in the README file.

The UI is exactly the same as the previous version, but this was just a strategically decision to ease the presentation to the Transmission members. With the new stack it'll be easier to implement whatever UI refactor if the community agree.

**Comment by SpaceK33z** [comment]
Okay, thanks for your answer! I'll try it soon.
