### ISSUE TITLE
Can not set Transmission server IP

### ISSUE THREAD

**Issue by nii236** [fcsonline/react-transmission#28]
My transmission server is on another machine, yet the app expects localhost. Is there a way to override this?

**Comment by edulan** [comment]
Hi @nii236

Though the app is configured to be used in the same host, you can easily change the server you like to point to. Check this line:

https://github.com/fcsonline/react-transmission/blob/master/scripts/start.js#L260

You just need to set the `target` to the url you want.

It'd be cool to extract this configuration to environment variables, so there will be no need to change the code. If you like the idea don't hesitate to create a PR for it :wink:

**Comment by nii236** [comment]
Thanks!
