### ISSUE TITLE
Transmission-web Feature Parity

### ISSUE THREAD

**Issue by Secretmapper** [fcsonline/react-transmission#32]
Hello! Awesome work on the project.

Do we have any official list of things that doesn't work/need to achieve feature parity to the official transimssion-web gui?

**Comment by fcsonline** [comment]
First of all I want to say thank you for collaborating in this project. We really appreciate your effort. :grinning: 

In the Github Wiki, we have a list of all the incoming improvements we want to work in, if you want to check them out and start working in some of them, it could awesome!

In the last 2 months @edulan and me implemented almost all features to achieve 100% feature parity. We wanted to achieve this high percentage to show to the community that this is a realistic alternative to the the original client. The missing piece was the file treeview in the torrent inspector but is almost completed in this [pull request](https://github.com/fcsonline/react-transmission/pull/29).

We started this project following a main rule. The client should we the same from the user perspective and they should not see difference between them, or at least really small ones. If you have more ideas to improve the UI, we can talk about it. They could be as nice as the *drag&drop* support for torrent files that we added recently.

**Comment by Secretmapper** [comment]
No problem at all! I was looking to create a personal web theme for transmission (new user here!), and I was super happy to find react-transmission since it'll be way easier to develop a theme with it :) Thank you guys for the awesome work.

I don't think I have any idea for improvements for the UI, drag & drop is the only one I can think of. I do have a few UI ideas, but most of them are drastic and more fitting for a custom theme.

One idea I've thought of that could be integrated is service worker support. However service workers need an HTTPS connection to work, and the additional setup plus minimal advantages makes it not worth it IMO.

I'll definitely take note of the last point, I agree that we should make the migration as transparent as possible.

I'll just provide a permalink in the wiki for any other users who might land in this issue:
https://github.com/fcsonline/react-transmission/wiki

Thanks!
