### ISSUE TITLE
Modularize Preferences as own store

### ISSUE THREAD

**Issue by Secretmapper** [fcsonline/react-transmission#34]
It would be great to modularize preferences as it's own store (i.e. statusFilter).

This allows us to serialize preferences easily (say in localState) so reopening the client will show where the user dropped off in the app.

What do you guys think?

**Comment by fcsonline** [comment]
All preferences are stored in the server. If you reopen the client again, you should see the same values, shouldn't you?

I don't see which is the goal of storing preferences in localState.

**Comment by Secretmapper** [comment]
Playing around it more I think you are right. At first I was thinking we could store some client-only preferences on client (i.e. filter, compact vs list view) but they are too few to count.
